#!/usr/bin/env bash

# Exit on first error.
set -e

# Treat undefined environment variables as errors.
set -u

modprobe libcomposite

cd /sys/kernel/config/usb_gadget/
mkdir -p g1
cd g1

echo 0x1d6b > idVendor  # Linux Foundation
echo 0x0104 > idProduct # Multifunction Composite Gadget
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB    # USB2

STRINGS_DIR="strings/0x409"
mkdir -p "$STRINGS_DIR"
echo "6b65796d696d6570690" > "${STRINGS_DIR}/serialnumber"
echo "keymimepi" > "${STRINGS_DIR}/manufacturer"
echo "Generic USB HID" > "${STRINGS_DIR}/product"

# Create keyboard function
KEYBOARD_DIR="functions/hid.keyboard"
mkdir -p "$KEYBOARD_DIR"
echo 1 > "${KEYBOARD_DIR}/protocol" # Keyboard
echo 0 > "${KEYBOARD_DIR}/subclass" # No subclass
echo 8 > "${KEYBOARD_DIR}/report_length"
echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > "${KEYBOARD_DIR}/report_desc"

# Create mouse function
MOUSE_DIR="functions/hid.mouse"
mkdir -p "$MOUSE_DIR"
echo 1 > "${MOUSE_DIR}/protocol" # Mouse
echo 0 > "${MOUSE_DIR}/subclass" # No subclass
echo 5 > "${MOUSE_DIR}/report_length"
echo -ne '\x05\x01\x09\x02\xa1\x01\x09\x01\xa1\x00\x05\x09\x19\x01\x29\x03\x15\x00\x25\x01\x95\x03\x75\x01\x81\x02\x95\x01\x75\x05\x81\x03\x05\x01\x09\x30\x09\x31\x16\x00\x00\x26\xff\x7f\x75\x10\x95\x02\x81\x02\xc0\xc0' > "${MOUSE_DIR}/report_desc"

CONFIG_INDEX=1
CONFIGS_DIR="configs/c.${CONFIG_INDEX}"
mkdir -p "$CONFIGS_DIR"
echo 250 > "${CONFIGS_DIR}/MaxPower"

CONFIGS_STRINGS_DIR="${CONFIGS_DIR}/strings/0x409"
mkdir -p "$CONFIGS_STRINGS_DIR"
echo "Config ${CONFIG_INDEX}: HID Composite" > "${CONFIGS_STRINGS_DIR}/configuration"

ln -s "$KEYBOARD_DIR" "${CONFIGS_DIR}/"
ln -s "$MOUSE_DIR" "${CONFIGS_DIR}/"

ls /sys/class/udc > UDC

chmod 777 /dev/hidg0
chmod 777 /dev/hidg1
